DELETE FROM SYSMODULE WHERE Module_ID = '7017'
INSERT INTO SYSMODULE(Module_Id, Module_Parent, Module_Name, Module_NameE, Module_NameO, Stt, Picture, Module_Method, Module_Para, Is_Module, Show_On_Main, Is_Customize, Object_ID, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit) VALUES(7017, 7000, N'Cập nhật phiên bản mới nhất', N'Update new version', N'更新新版本', 7017, N'UpdateFile.png', N'Epoint.Controllers:Controllers.frmUpdateFile:Load', N'', 0, 0, 0, N'UPDATEFILE', N'ADMIN', N'ADMIN', '2015-12-26 10:19:22.953', '2016-12-22 14:14:54.427')


DELETE FROM SYSMODULE WHERE Module_ID = '9016'
INSERT INTO SYSMODULE(Module_Id, Module_Parent, Module_Name, Module_NameE, Module_NameO, Stt, Picture, Module_Method, Module_Para, Is_Module, Show_On_Main, Is_Customize, Object_ID, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit) VALUES(9016, 9000, N'Upload file cho phiên bản mới nhất', N'Upload file for new version', N'上傳新版本的文件', 9016, N'UpdateFile.png', N'Epoint.Controllers:Controllers.frmRESOURCE_VER:Load', N'', 0, 0, 0, N'UPDATEFILE', N'ADMIN', N'ADMIN', '2015-12-26 10:19:22.953', '2016-12-22 15:26:47.567')


---Zone

DELETE FROM SYSZONE WHERE Zone = 'RESOURCE_VER'
INSERT INTO SYSZONE(Zone, Zone_Parent, Resize_Rate, Sortable, Description, Expand, Is_Customize, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit) VALUES(N'RESOURCE_VER', N'SYSTEM', 100, 1, N'RESOURCE_VER', 1, 0, N'ADMIN', N'ADMIN', '2013-08-12 11:49:28.240', '2016-02-23 16:52:11.560')


DELETE FROM SYSCOLUMN WHERE Zone = 'RESOURCE_VER'
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'DESCRIPTION', 150, N'T', 0, 1, N'Description', N'Description', N'明細', 7, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:57:12.353', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'FILE_ID', 100, N'T', 0, 1, N'File ID', N'File ID', N'代碼文件', 1, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 13:03:59.053', '2015-11-12 23:55:40.530', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'FILE_NAME', 100, N'T', 0, 1, N'File Name', N'File name', N'文件名', 2, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:55:46.960', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'FILE_TAG', 100, N'T', 0, 1, N'File Tag', N'File type', N'文件', 4, N'3', 0, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:56:02.903', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'FILE_TYPE', 100, N'T', 0, 1, N'File Type', N'File type', N'文件', 3, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:55:53.887', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'NGAY_KY', 80, N'D', 0, 1, N'Sign date', N'Contract date', N'簽約日期', 6, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:57:03.593', 0, N'', 0, N'', 0, 0, N'', N'')
INSERT INTO SYSCOLUMN(Zone, Column_ID, Width, Type, Scale, Resizable, Description, Description_E, Description_O, Stt, Show_Type, Visible, Is_Customize, COLOR, User_Crtd, User_Edit, Ngay_Crtd, Ngay_Edit, AutoFilter, KeyFilter, Upper_Case, KeyValid, Is_Require, UseDfValidating, TextFilter, ColumnList_ViewFilter) VALUES(N'RESOURCE_VER', N'NGUOI_KY', 120, N'T', 0, 1, N'Signatory', N'Signer', N'簽名人', 5, N'3', 1, 0, N'', N'ADMIN', N'ADMIN', '2013-08-12 11:49:55.643', '2015-11-12 23:56:54.530', 0, N'', 0, N'', 0, 0, N'', N'')
