USE [Epoint0]
GO

/****** Object:  Table [dbo].[SYSRESOURCES_VER]    Script Date: 17/01/2017 1:00:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SYSRESOURCES_VER](
	[File_ID] [varchar](200) NOT NULL,
	[Catalog] [varchar](20) NOT NULL,
	[File_Name] [nvarchar](200) NOT NULL,
	[File_Type] [varchar](10) NOT NULL,
	[File_Tag] [varchar](10) NOT NULL CONSTRAINT [DF__SYSRESOURCEVER__File___754B42FF]  DEFAULT (''),
	[File_Content] [varbinary](max) NULL,
	[Description] [nvarchar](250) NOT NULL CONSTRAINT [DF__SYSRESOURCEVER__Descr__74571EC6]  DEFAULT (''),
	[Ma_Nhom] [varchar](20) NOT NULL CONSTRAINT [DF__SYSRESOURCEVER__Ma_Nh__02DB139E]  DEFAULT (''),
	[Duyet] [bit] NOT NULL CONSTRAINT [DF__SYSRESOUR__Duyet__349E2312]  DEFAULT ((0)),
	[Ngay_Ky] [datetime] NOT NULL CONSTRAINT [DF__SYSRESOUR__Ngay___3592474B]  DEFAULT (''),
	[Nguoi_Ky] [nvarchar](100) NOT NULL CONSTRAINT [DF__SYSRESOUR__Nguoi__36866B84]  DEFAULT (''),
 CONSTRAINT [PK__SYSRESOURCEVER__49C04C7A726ED654] PRIMARY KEY CLUSTERED 
(
	[File_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


