//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.Systems.Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epoint.Systems.Commons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap accepted {
            get {
                object obj = ResourceManager.GetObject("accepted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap accepted1 {
            get {
                object obj = ResourceManager.GetObject("accepted1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap accepted11 {
            get {
                object obj = ResourceManager.GetObject("accepted11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap accepted2 {
            get {
                object obj = ResourceManager.GetObject("accepted2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Background_E {
            get {
                object obj = ResourceManager.GetObject("Background_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Background_V {
            get {
                object obj = ResourceManager.GetObject("Background_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Background1 {
            get {
                object obj = ResourceManager.GetObject("Background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calculator {
            get {
                object obj = ResourceManager.GetObject("Calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Chart {
            get {
                object obj = ResourceManager.GetObject("Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap close3 {
            get {
                object obj = ResourceManager.GetObject("close3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Design {
            get {
                object obj = ResourceManager.GetObject("Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF exists(SELECT * from sys.objects where name = &apos;sp_Process_Dvcs&apos; AND type = &apos;P&apos;) DROP PROC sp_Process_Dvcs
        ///IF exists(SELECT * from sys.objects where name = &apos;sp_Process_DvcsPC&apos; AND type = &apos;P&apos;) DROP PROC sp_Process_DvcsPC.
        /// </summary>
        public static string Drop_Process {
            get {
                return ResourceManager.GetString("Drop_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dvcs {
            get {
                object obj = ResourceManager.GetObject("Dvcs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	--EXEC(&apos;&apos;ALTER TABLE SYSMEMBER ADD CheckPass VARBINARY(MAX)&apos;&apos;)
        ///
        ///	EXEC(&apos;&apos;UPDATE SYSMEMBER SET CheckPass = dbo.fn_Encrypt(Password)&apos;&apos;)
        ///
        ///	
        ///
        ///
        ///.
        /// </summary>
        public static string fn_ChangePass {
            get {
                return ResourceManager.GetString("fn_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE FUNCTION [dbo].[fn_Decrypt]
        ///(
        ///	@CheckPass VARBINARY(MAX)
        ///)
        ///RETURNS NVARCHAR(MAX)
        ///WITH ENCRYPTION
        ///AS
        ///BEGIN
        ///
        ///	DECLARE @_MyPass NVARCHAR(20)
        ///
        ///	SET @_MyPass = &apos;&apos;E&apos;&apos; + &apos;&apos;P&apos;&apos; + &apos;&apos;O&apos;&apos; + &apos;&apos;I&apos;&apos;  + &apos;&apos;T&apos;&apos;
        ///
        ///	RETURN CONVERT(NVARCHAR(MAX), DecryptByPassPhrase(@_MyPass, @CheckPass))
        ///
        ///END
        ///.
        /// </summary>
        public static string fn_Decrypt {
            get {
                return ResourceManager.GetString("fn_Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE FUNCTION [dbo].[fn_Encrypt]
        ///(
        ///	@Password NVARCHAR(MAX)
        ///)
        ///RETURNS VARBINARY(MAX)
        ///WITH ENCRYPTION
        ///AS
        ///BEGIN
        ///
        ///	DECLARE @_MyPass NVARCHAR(20)
        ///
        ///	SET @_MyPass = &apos;&apos;E&apos;&apos; + &apos;&apos;P&apos;&apos; + &apos;&apos;O&apos;&apos; + &apos;&apos;I&apos;&apos;  + &apos;&apos;T&apos;&apos;
        ///	RETURN EncryptByPassPhrase(@_MyPass, @Password)
        ///
        ///END
        ///.
        /// </summary>
        public static string fn_Encrypt {
            get {
                return ResourceManager.GetString("fn_Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loadingQ {
            get {
                object obj = ResourceManager.GetObject("loadingQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logfile {
            get {
                object obj = ResourceManager.GetObject("Logfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview {
            get {
                object obj = ResourceManager.GetObject("Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap print_48 {
            get {
                object obj = ResourceManager.GetObject("print_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QuickReport {
            get {
                object obj = ResourceManager.GetObject("QuickReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reload_icon {
            get {
                object obj = ResourceManager.GetObject("reload_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC sp_GetLicensePC 
        ///(
        ///	@Ma_Dvcs VARCHAR(30) = &apos;&apos;E01&apos;&apos;,
        ///	@Drive_Info VARCHAR(100) = &apos;&apos;&apos;&apos;
        ///)
        ///WITH ENCRYPTION
        ///AS
        ///
        ///BEGIN
        ///				DECLARE @_Pc_Name VARCHAR(30) 				
        ///				DECLARE @_Dvcs VARCHAR(30) 
        ///				DECLARE @_CustID VARCHAR(30) 
        ///				DECLARE @_Con_Server VARCHAR(100)
        ///				DECLARE @_DataBase_Name VARCHAR(100)
        ///				DECLARE @_ServerName VARCHAR(100)
        ///				
        ///				
        ///				
        ///				SELECT @_DataBase_Name = DB_NAME() 
        ///				SELECT @_ServerName  = CAST(SERVERPROPERTY(&apos;&apos;ServerName&apos;&apos;) AS VARCHAR(100))
        ///				SELECT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sp_GetLicensePC {
            get {
                return ResourceManager.GetString("sp_GetLicensePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROC sp_Process_Dvcs
        ///(
        ///	@Ma_Dvcs VARCHAR(3) = &apos;&apos;E01&apos;&apos;,
        ///	@Drive_Info VARCHAR(100) = &apos;&apos;&apos;&apos;
        ///)
        ///--WITH ENCRYPTION
        ///AS
        ///	--RETURN 
        ///BEGIN
        ///	
        ///		
        ///		
        ///		BEGIN TRY
        ///				DECLARE @_Pc_Name VARCHAR(30) 
        ///				DECLARE @_Dvcs VARCHAR(30) 
        ///				DECLARE @_CustID VARCHAR(30) 
        ///				DECLARE @_Con_Server VARCHAR(100)
        ///				DECLARE @_DataBase_Name VARCHAR(100)
        ///				DECLARE @_Server_Name VARCHAR(100)
        ///				
        ///				
        ///				
        ///				SELECT @_DataBase_Name = DB_NAME() 
        ///				SELECT @_Server_Name  = CAST(SERVERPROPERTY(&apos;&apos;ServerNa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sp_Process_Dvcs {
            get {
                return ResourceManager.GetString("sp_Process_Dvcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[sp_Process_Dvcs]
        ///(
        ///	@Ma_Dvcs VARCHAR(3) = &apos;E01&apos;,
        ///	@Drive_Info VARCHAR(100) = &apos;E63374FA&apos;
        ///)
        ///WITH ENCRYPTION
        ///AS
        ///	--RETURN 
        ///BEGIN
        ///	
        ///		
        ///		
        ///		BEGIN TRY
        ///				DECLARE @_Pc_Name VARCHAR(30) 
        ///				DECLARE @_Dvcs VARCHAR(30) 
        ///				DECLARE @_CustID VARCHAR(30) 
        ///				DECLARE @_Con_Server VARCHAR(100)
        ///				DECLARE @_DataBase_Name VARCHAR(100)
        ///				DECLARE @_Server_Name VARCHAR(100)
        ///				
        ///				
        ///				
        ///				SELECT @_DataBase_Name = DB_NAME() 
        ///				SELECT @_Server_Name  = CAST(SERVERPROPERTY(&apos;S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sp_Process_Lics {
            get {
                return ResourceManager.GetString("sp_Process_Lics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[sp_Process_DvcsPC]
        ///(
        ///	@Ma_Dvcs VARCHAR(3) = &apos;E01&apos;,
        ///	@Drive_Info VARCHAR(100) = &apos;5EA9E0EB&apos;
        ///)
        ///WITH ENCRYPTION
        ///AS
        ///	--RETURN 
        ///BEGIN
        ///	
        ///		
        ///		
        ///		BEGIN TRY
        ///				DECLARE @_Pc_Name VARCHAR(30) 
        ///				DECLARE @_Dvcs VARCHAR(30) 
        ///				DECLARE @_CustID VARCHAR(30) 
        ///				DECLARE @_Con_Server VARCHAR(100)
        ///				DECLARE @_DataBase_Name VARCHAR(100)
        ///				DECLARE @_Server_Name VARCHAR(100)
        ///				
        ///				
        ///				
        ///				SELECT @_DataBase_Name = DB_NAME() 
        ///				SELECT @_Server_Name  = CAST(SERVERPROPERTY( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sp_Process_LicsPC {
            get {
                return ResourceManager.GetString("sp_Process_LicsPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sum1 {
            get {
                object obj = ResourceManager.GetObject("Sum1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TeamViewer {
            get {
                object obj = ResourceManager.GetObject("TeamViewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ViewReport {
            get {
                object obj = ResourceManager.GetObject("ViewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
