//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epoint.Controllers.MaintenanceDB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsMaintenanceDB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsMaintenanceDB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epoint.Controllers.MaintenanceDB.rsMaintenanceDB", typeof(rsMaintenanceDB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE Sp_ConfigAutoBackup
        ///(
        ///	@JobName NVARCHAR(100) = &apos;&apos;,
        ///	@DatabaseName VARCHAR(50) = &apos;&apos;,
        ///	@BackupPath NVARCHAR(50) = &apos;&apos;,	
        ///	@ServerName NVARCHAR(50) = &apos;&apos;,
        ///	@ActiveStartDate INT = 20000101,
        ///	@ActiveStartTime INT = 0, -- 12h:AM
        ///	@freq_interval INT = 32-- thu 6
        ///)
        ///WITH ENCRYPTION
        ///AS
        ///BEGIN
        ///
        ///	--------sp_add_job-----------
        ///	IF EXISTS (SELECT Job_Id FROM sysjobs WHERE Name = @JobName)
        ///		EXEC sp_delete_job @job_name = @JobName
        ///
        ///	EXEC  msdb.dbo.sp_add_job @job_name= @JobName,
        ///			@enable [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sp_ConfigAutoBackup {
            get {
                return ResourceManager.GetString("Sp_ConfigAutoBackup", resourceCulture);
            }
        }
    }
}
